name: elandguard
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  geolocator:
  http: ^0.13.4
  json_annotation: ^4.0.1
  json_string: ^2.0.1
  pin_entry_text_field: ^0.1.4
  grouped_list: ^4.1.0
  toast: ^0.1.5
  uuid: ^3.0.4
  shared_preferences: ^2.0.7
  fl_chart: ^0.40.0
  flutter_map: ^0.11.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.4
  path: ^1.8.0
  # qrscan: ^0.3.0
  # permission_handler: ^8.1.6
#  barcode_scan_fix: ^1.0.2
  latlong: ^0.6.1
#  map_controller: ^0.9.0
  proj4dart: ^1.0.5
  geocore: ^0.7.0
  image_picker: ^0.8.4+4
  image_cropper:
  google_fonts: ^2.1.0
  flash: ^2.0.3
  otp_text_field: ^1.1.1
  flutter_native_splash: ^1.2.3
  splashscreen: ^1.3.5
  webview_flutter: ^2.3.1
  provider: ^6.0.1
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  permission_handler: ^10.0.0
  google_maps_flutter: ^2.1.1
  html: ^0.15.0
  intl_phone_number_input: ^0.7.0+2
  intl_phone_field: ^2.1.0
  flutter_barcode_scanner: ^2.0.0
  share_plus: ^4.3.0
#  advance_pdf_viewer: ^2.0.0
  flutter_pdfview: ^1.2.1
#  international_phone_input: ^1.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/
   - images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
